NAME=GitHub Explorer

ID=github

VERSION=1.0.0

AUTHOR=Fabio Brito

DESCRIPTION=Pesquisa, análise e gerenciamento de projetos GitHub.

CATEGORY=Development

MENU=menu.sh

INSTALL=install.sh

UPDATE=update.sh

UNINSTALL=uninstall.sh
