plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.agentostudio.mobiletermux'
    compileSdk 35

    defaultConfig {
        applicationId 'br.com.agentostudio.mobileconnector'
        minSdk 23
        targetSdk 28
        versionCode 3
        versionName '0.3.0'
    }

    buildTypes {
        debug {
            debuggable true
        }
    }
}
